project_seo_tool/app_seo_tool/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django.urls import path
from django.contrib.auth import views as auth_views

from app_seo_tool import views as app_seo_views


urlpatterns = [

    # General urls
    path('', app_seo_views.home, name='home'),

    path('acceso/', app_seo_views.custom_login, name='custom_login'),
    path('desconectar/', auth_views.LogoutView.as_view(), name='logout'),
    path('activacion/<uidb64>/<token>/', app_seo_views.activation, name='activation'),
    path('password_reset/', app_seo_views.password_reset, name='password_reset'),
    path('password_reset_form/<uidb64>/<token>/', app_seo_views.password_reset_form, name='password_reset_form'),

    path('resultados/', app_seo_views.result_list, name='result_list'),
    #path('resultados/filtrar/', app_seo_views.result_filter, name='result_filter'),#

    path('busquedas/', app_seo_views.search_list, name='search_list'),
    #path('busquedas/crear/', app_seo_views.search_create, name='search_create'),
    #path('busquedas/filtrar/', app_seo_views.search_filter, name='search_filter'),
]

project_seo_tool/project_seo_tool/urls.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-

from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView

from project_seo_tool import settings
from app_seo_tool import urls as app_seo_urls

admin.site.site_header = 'CG3 SEO'
admin.autodiscover()

urlpatterns = [

    # Redirect
    path('', RedirectView.as_view(url='/panel/home/')),

    # App Urls
    path('panel/', include((app_seo_urls, 'panel'), namespace='panel')),

    # Admin Urls
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_seo_tool/templates/base.html
{% load static %}

{% block extrahead %}
{% endblock %}


<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>CG3 SEO</title>

    <!-- jQuery UI CSS -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Icons FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesomeicons.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block stylesheet %}
    {% endblock %}

  </head>
  <body>

    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}

    <!-- jQuery JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <!-- Popper JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <!--<script type="text/javascript" src='https://unpkg.com/popper.js/dist/umd/popper.min.js'></script>-->

    <!-- jQuery UI JS -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- FontAwesome Icons -->
    <script src="{% static 'js/fontawesomeicons.js' %}"></script>

    <!-- Custom JS -->
    <script src="{% static 'js/functions.js' %}"></script>

    {% block javascript %}
    {% endblock javascript %}

  </body>
</html>

project_seo_tool/templates/create.html
{% load static %}
{% load storage_tags %}

<div class="modal-dialog modal-lg">
  <div class="modal-content">
    {% get_url urls 'create' as element_create %}
    <form method="POST" action="{% url element_create %}" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="modal-header">
        <h4 class="modal-title">{{ title }}</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% include 'form.html' %}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-outline-primary">Crear</button>
      </div>
    </form>
  </div>
</div>

project_seo_tool/templates/delete.html
{% load storage_tags %}

<div class="modal-dialog modal-lg">
  <div class="modal-content">

    {% get_url urls 'delete' as element_delete %}
    <form method="POST" action="{% url element_delete element.id %}">
      {% csrf_token %}

    <div class="modal-header">
      <h4 class="modal-title">{{ title }}</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">

      <p>¿ Seguro que quieres borrarlo ?</p>
      {% include 'form.html' %}

    </div>
    <div class="modal-footer">
      <button type="submit" class="btn btn-outline-danger">
        Borrar
      </button>
    </div>

    </form>

  </div>
</div>

project_seo_tool/templates/footer.html
<footer class="footer text-center">
  <div class="container">
    <span>STORAGE & GO © <script>document.write(new Date().getFullYear());</script> Todos los derechos reservados.</span><br>
    <span> { } with &hearts; by: <a href="http://preconcebido.com" target="_blank">PRECONCEBIDO.COM</a></span>
  </div>
</footer>

project_seo_tool/templates/form.html
{% load widget_tweaks %}
{% load static %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>

    {{ field|add_class:"form-control" }}

    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}

    <!-- Help textt -->
    
  </div>
{% endfor %}

{% block javascript %}
  <script src="{% static 'js/functions.js' %}"></script>
{% endblock %}

project_seo_tool/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <div>
        <img class="img-fluid" src="{% static 'img/banner.jpg' %}" alt="">
      </div>
    </div>
	</div>
</div>

{% endblock content %}

project_seo_tool/templates/list.html
{% extends "base.html" %}

{% load static %}
{% load storage_tags %}
{% load widget_tweaks %}

{% block content %}

<div class="container-fluid">

  <!-- Element List -->
  <div class="row custom_row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <div class="container-fluid">
            <div class="row">
              <div class="col-8">
                <h5>{{ title }}</h5>
              </div>
              <div class="col-4">
                {% get_url urls 'create' as element_create %}
                {% check_permission user.username type="Modelo" action="Crear" model=model as aux %}
                {% if aux or user.is_superuser %}
                <button type="button" onclick="return openCustomModal('{% url element_create %}')" class="btn btn-outline-primary float-right btn-sm">
                  <span class="fas fa-plus"></span>
                </button>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="card-body custom-card-body">
          {% if elements|length > 0 %}
            <div class="table-responsive">
              <table class="table table-striped table-hover custom-table">
                <thead class="thead-light">
                  <tr>
                    {% for field in fields %}
                      <th class="text-center">
                        {{ field.verbose_name }}

                        <div class="dropdown">
                          <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="?page={{page}}&order={{ field.name }}">asc</a></li>
                            <li><a href="?page={{page}}&order=-{{ field.name }}">desc</a></li>
                          </ul>
                        </div>

                      </th>
                    {% endfor %}
                    <th class="text-center">Opciones</th>
                  </tr>
                </thead>
                <tbody>
                  {% for element in elements %}

                    {% if element.status == 'Completada' or element.status == 'Aprobado' %}
                      <tr class="table-success">
                    {% elif element.status == 'Pendiente' %}
                      <tr class="table-warning">
                    {% elif element.status == 'Cancelado'%}
                      <tr class="table-danger">
                    {% else %}
                      {% if forloop.counter|divisibleby:"2" %}
                        <tr class="table-default">
                      {% else %}
                        <tr class="table-active">
                      {% endif %}
                    {% endif %}

                      {% for value in element.fields_values %}
                        <td class="align-middle text-center">{{ value }}</td>
                      {% endfor %}
                      <td class="text-center">
                        <div class="dropdown">
                          <a href="btn btn-secondary" id="option_button" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="fas fa-bars"></span>
                          </a>
                          <div class="dropdown-menu" arial-labelledby="option_button">

                            {% get_url urls 'view' as element_view %}
                            {% check_permission user.username type="Objeto" action="Ver" model=model object=element.id as aux %}
                            {% if aux or user.is_superuser %}
                            <a class="dropdown-item">
                              <button type="button" onclick="return openCustomModal('{% url element_view element.id %}')" class="btn btn-outline-primary float-right btn-sm">
                                Ver
                                <span class="fas fa-eye"></span>
                              </button>
                            </a>
                            {% endif %}

                            {% get_url urls 'update' as element_update %}
                            {% check_permission user.username type="Objeto" action="Modificar" model=model object=element.id as aux %}
                            {% if aux or user.is_superuser %}
                            <a class="dropdown-item">
                              <button type="button" onclick="return openCustomModal('{% url element_update element.id %}')" class="btn btn-outline-primary float-right btn-sm">
                                Editar
                                <span class="fas fa-pencil-alt"></span>
                              </button>
                            </a>
                            {% endif %}

                            {% get_url urls 'delete' as element_delete %}
                            {% check_permission user.username type="Objeto" action="Borrar" model=model object=element.id as aux %}
                            {% if aux or user.is_superuser %}
                            <a class="dropdown-item">
                              <button type="button" onclick="return openCustomModal('{% url element_delete element.id %}')" class="btn btn-outline-primary float-right btn-sm">
                                Borrar
                                <span class="fas fa-trash"></span>
                              </button>
                            </a>
                            {% endif %}
                          </div>
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          {% else %}
            <p>No hay elementos ...</p>
          {% endif %}
        </div>
        <div class="card-footer">

          <!-- Pagination -->
          <ul class="pagination justify-content-center">
            {% if elements.has_previous %}
              <li class="page-item">
                <a href="?page=1&order={{order}}">
                  <button type="button" class="btn btn-outline-primary float-right">
                    <span class="fas fa-angle-double-left"></span>
                  </button>
                </a>
              </li>
              <li class="page-item">
                <a href="?page={{ elements.previous_page_number }}&order={{order}}">
                  <button type="button" class="btn btn-outline-primary float-right">
                    <span class="fas fa-angle-left"></span>
                  </button>
                </a>
              </li>
            {% endif %}
            <li class="page-item">
              <a href="#">
                <button type="button" class="btn btn-outline-primary float-right btn-sm">
                  {{ elements.number }}
                </button>
              </a>
            </li>
            {% if elements.has_next %}
              <li class="page-item">
                <a href="?page={{ elements.next_page_number }}&order={{order}}">
                  <button type="button" class="btn btn-outline-primary float-right">
                    <span class="fas fa-angle-right"></span>
                  </button>
                </a>
              </li>
              <li class="page-item">
                <a href="?page={{ elements.paginator.num_pages }}&order={{order}}">
                  <button type="button" class="btn btn-outline-primary float-right">
                    <span class="fas fa-angle-double-right"></span>
                  </button>
                </a>
              </li>
            {% endif %}
          </ul>
        </div>

      </div>
    </div>
  </div>

</div>

<!-- Modal -->
<div class="modal fade" id="custom-modal" role="dialog">
</div>

{% endblock content %}

project_seo_tool/templates/login.html
{% extends "base.html" %}
{% load static %}


{% block content %}

  <div class="container">
    <div class="row">
      <div class="col">
        <h3>Acceso a usuarios</h3>

        <form method="POST" action="{% url 'panel:custom_login' %}">
          {% csrf_token %}

          {% include 'form.html' %}

          <button type="submit" class="btn btn-outline-primary">Acceder</button>
        </form>
      </div>
    </div>
  </div>
  <hr>

{% endblock content %}

project_seo_tool/templates/navbar.html
{% load static %}

<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <!-- Brand & Logo -->
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'panel:home' %}">CG3 SEO</a>
    </div>

    <!-- Main Menu -->
    <div class="collapse navbar-collapse" id="generalMenu">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'panel:result_list'%}">Resultados</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'panel:search_list'%}">Búsquedas</a>
          </li>
        </ul>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#generalMenu" aria-controls="generalMenu" aria-expanded="true" aria-label="Toggle navigation">
      <span class="fas fa-bars" style="font-size: 20px;"></span>
    </button>

    <!-- Profile Icon / Menu -->
    <div class="btn-group">
      <button type="button" class="btn btn-outline-primary dropdown-toggle btn-sm" id="profileMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="fas fa-user" style="font-size: 20px;"></span>
      </button>

      <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="profileMenu">
        {% if not user.is_authenticated %}
          <li>
            <a class="dropdown-item" href="{% url 'panel:custom_login' %}">Acceder</a>
          </li>
        {% else %}
        <li>
          <a class="dropdown-item"
            <button type="button" class="btn btn-outline-primary float-right btn-sm">
              {{ user.username }}
            </button>
          </a>
        </li>
        <li>
          <a class="dropdown-item" href="#">Fichar</a>
        </li>
        <li>
          <a class="dropdown-item" href="#">Cambiar Contraseña</a>
        </li>
        <li>
          <div class="dropdown-divider"></div>
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'panel:logout'%}">Cerrar Sesión</a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>




<!-- -->

project_seo_tool/templates/password_reset.html
{% extends "base.html" %}
{% load static %}


{% block content %}

  <div class="container">
    <div class="row">
      <div class="col">
        <h3>Restaurar Contraseña</h3>

        <form method="POST" action="{% url 'cms:password_reset' %}">
          {% csrf_token %}

          <!--<div style="display:none;"><input type="hidden" name="_method" value="POST"/></div>
          <div class="form-group required"><label for="UserUsername">Correo</label><input name="data[User][username]" class="form-control" placeholder="@" type="text" id="UserUsername" required="required"/></div>
          <div class="form-group required"><label for="UserPassword">Contraseña</label><input name="data[User][password]" class="form-control" placeholder="********" type="password" id="UserPassword" required="required"/></div>
          <button type="submit" label="" class="btn btn-outline-primary">Entrar</button>
        </form>-->
          {% include 'form.html' %}

          <!--<a href="{% url 'cms:password_reset' %}" class="btn btn-link btn-small">¿Olvidaste tu contraseña?</a>-->

          <button type="submit" class="btn btn-outline-primary">Restablecer</button>
        </form>
      </div>
    </div>
  </div>
  <hr>

{% endblock content %}

project_seo_tool/templates/password_reset_form.html
{% extends "base.html" %}
{% load static %}


{% block content %}

  <div class="container">
    <div class="row">
      <div class="col">
        <h3>Restaurar Contraseña</h3>

        <form method="POST" action="{% url 'cms:password_reset_form' uidb64=user token=None %}">
          {% csrf_token %}

          <!--<div style="display:none;"><input type="hidden" name="_method" value="POST"/></div>
          <div class="form-group required"><label for="UserUsername">Correo</label><input name="data[User][username]" class="form-control" placeholder="@" type="text" id="UserUsername" required="required"/></div>
          <div class="form-group required"><label for="UserPassword">Contraseña</label><input name="data[User][password]" class="form-control" placeholder="********" type="password" id="UserPassword" required="required"/></div>
          <button type="submit" label="" class="btn btn-outline-primary">Entrar</button>
        </form>-->
          {% include 'form.html' %}

          <!--<a href="{% url 'cms:password_reset' %}" class="btn btn-link btn-small">¿Olvidaste tu contraseña?</a>-->

          <button type="submit" class="btn btn-outline-primary">Restablecer</button>
        </form>
      </div>
    </div>
  </div>
  <hr>

{% endblock content %}

project_seo_tool/templates/update.html
{% load static %}
{% load storage_tags %}

<div class="modal-dialog modal-lg">
  <div class="modal-content">
    {% get_url urls 'update' as element_update %}
    <form method="POST" action="{% url element_update element.id %}" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="modal-header">
        <h4 class="modal-title">{{ title }}</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% include 'form.html' %}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-outline-primary">Guardar</button>
      </div>
    </form>
  </div>
</div>

project_seo_tool/templates/view.html
{% load static %}
{% load storage_tags %}

<div class="modal-dialog modal-lg">
  <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title">{{ title }}</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        {% for key, value in element.fields_values.items %}
          <p><b>{{ key }}:</b> {{ value }}</p>
        {% endfor %}

        <!-- If Room Detail -->
        {% if model.meta.verbose_name == 'Sala' %}
          <p><b>Mapa de Sala:</b></p>
          <div class="container-fluid">
            {% setValue 0 as aux %}
            {% for item in room_map %}
              {% if item.y == 0 %}
                {% if item.x != aux %}
                  </div>
                {% endif %}
                <div class="row" style="height: 20%;">
              {% endif %}
              {% if item.status == 'Disponible' %}
                <div class="col sala empty" onclick="return openCustomModal('{% url 'panel:container_view' item.id %}')">
              {% else %}
                <div class="col sala full" onclick="return openCustomModal('{% url 'panel:container_view' item.id %}')">
              {% endif %}
              <p>{{ item.id }}</p>
              </div>
              {% setValue item.x as aux %}
            {% endfor %}
            </div>
          </div>
        {% endif %}

        </div>

        <!-- If Room Detail -->
        {% if model.meta.verbose_name == 'Sala' %}
          <div class="modal-footer">

            {% get_url urls 'update' as element_update %}
            {% check_permission user.username type="Atributo" action="Modificar" model=model object=element.id as aux %}
            {% if aux or user.is_superuser %}
            <button type="submit" onclick="return openCustomModal('{% url element_update element.id %}')" class="btn btn-outline-primary">Editar</button>
            {% endif %}

            <!--{% if element.status == 'Cerrada' %}
              <button type="submit" class="btn btn-outline-primary">Abrir</button>
            {% else %}
              <button type="submit" class="btn btn-outline-danger">Cerrar</button>
            {% endif %}-->

          </div>
        {% endif %}

      </div>
  </div>
</div>